# Generated by Django 2.2.1 on 2019-05-18 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=30)),
                ('serialNumber', models.CharField(blank=True, max_length=40)),
                ('acquiredDate', models.DateTimeField(blank=True, null=True)),
                ('purchasePrice', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('assetImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('rentStatus', models.CharField(choices=[('Not Rented', '****Not Rented****'), ('Rented', 'This Asset is rented')], default='Not Rented', max_length=30)),
                ('assetMovement', models.CharField(choices=[('No', '*******No*******'), ('Yes', 'Asset in Motion')], default='No', max_length=30)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='assets.Category')),
            ],
        ),
    ]
