# Generated by Django 2.2.1 on 2019-05-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='categoryName',
            field=models.CharField(choices=[('', '*************Choose Category************'), ('Laptops', 'Laptops'), ('Printers', 'Printers'), ('Furniture', 'Furniture'), ('Cars', 'Cars'), ('Trucks', 'Trucks'), ('Others', 'Others')], max_length=30),
        ),
    ]
